/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PlayerService } from "../player.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PlayerCreateInput } from "./PlayerCreateInput";
import { Player } from "./Player";
import { PlayerFindManyArgs } from "./PlayerFindManyArgs";
import { PlayerWhereUniqueInput } from "./PlayerWhereUniqueInput";
import { PlayerUpdateInput } from "./PlayerUpdateInput";
import { GameActionFindManyArgs } from "../../gameAction/base/GameActionFindManyArgs";
import { GameAction } from "../../gameAction/base/GameAction";
import { GameActionWhereUniqueInput } from "../../gameAction/base/GameActionWhereUniqueInput";
import { PlayerGroupFindManyArgs } from "../../playerGroup/base/PlayerGroupFindManyArgs";
import { PlayerGroup } from "../../playerGroup/base/PlayerGroup";
import { PlayerGroupWhereUniqueInput } from "../../playerGroup/base/PlayerGroupWhereUniqueInput";
import { PlayerLocationFindManyArgs } from "../../playerLocation/base/PlayerLocationFindManyArgs";
import { PlayerLocation } from "../../playerLocation/base/PlayerLocation";
import { PlayerLocationWhereUniqueInput } from "../../playerLocation/base/PlayerLocationWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PlayerControllerBase {
  constructor(
    protected readonly service: PlayerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Player })
  @nestAccessControl.UseRoles({
    resource: "Player",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPlayer(@common.Body() data: PlayerCreateInput): Promise<Player> {
    return await this.service.createPlayer({
      data: data,
      select: {
        createdAt: true,
        email: true,
        id: true,
        nickname: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Player] })
  @ApiNestedQuery(PlayerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Player",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async players(@common.Req() request: Request): Promise<Player[]> {
    const args = plainToClass(PlayerFindManyArgs, request.query);
    return this.service.players({
      ...args,
      select: {
        createdAt: true,
        email: true,
        id: true,
        nickname: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Player })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Player",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async player(
    @common.Param() params: PlayerWhereUniqueInput
  ): Promise<Player | null> {
    const result = await this.service.player({
      where: params,
      select: {
        createdAt: true,
        email: true,
        id: true,
        nickname: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Player })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Player",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePlayer(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() data: PlayerUpdateInput
  ): Promise<Player | null> {
    try {
      return await this.service.updatePlayer({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          id: true,
          nickname: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Player })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Player",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePlayer(
    @common.Param() params: PlayerWhereUniqueInput
  ): Promise<Player | null> {
    try {
      return await this.service.deletePlayer({
        where: params,
        select: {
          createdAt: true,
          email: true,
          id: true,
          nickname: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/gameActions")
  @ApiNestedQuery(GameActionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "GameAction",
    action: "read",
    possession: "any",
  })
  async findGameActions(
    @common.Req() request: Request,
    @common.Param() params: PlayerWhereUniqueInput
  ): Promise<GameAction[]> {
    const query = plainToClass(GameActionFindManyArgs, request.query);
    const results = await this.service.findGameActions(params.id, {
      ...query,
      select: {
        actionType: true,
        createdAt: true,
        id: true,
        payload: true,

        player: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/gameActions")
  @nestAccessControl.UseRoles({
    resource: "Player",
    action: "update",
    possession: "any",
  })
  async connectGameActions(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: GameActionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      gameActions: {
        connect: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/gameActions")
  @nestAccessControl.UseRoles({
    resource: "Player",
    action: "update",
    possession: "any",
  })
  async updateGameActions(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: GameActionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      gameActions: {
        set: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/gameActions")
  @nestAccessControl.UseRoles({
    resource: "Player",
    action: "update",
    possession: "any",
  })
  async disconnectGameActions(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: GameActionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      gameActions: {
        disconnect: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/playerGroups")
  @ApiNestedQuery(PlayerGroupFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PlayerGroup",
    action: "read",
    possession: "any",
  })
  async findPlayerGroups(
    @common.Req() request: Request,
    @common.Param() params: PlayerWhereUniqueInput
  ): Promise<PlayerGroup[]> {
    const query = plainToClass(PlayerGroupFindManyArgs, request.query);
    const results = await this.service.findPlayerGroups(params.id, {
      ...query,
      select: {
        createdAt: true,

        group: {
          select: {
            id: true,
          },
        },

        id: true,

        player: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/playerGroups")
  @nestAccessControl.UseRoles({
    resource: "Player",
    action: "update",
    possession: "any",
  })
  async connectPlayerGroups(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: PlayerGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      playerGroups: {
        connect: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/playerGroups")
  @nestAccessControl.UseRoles({
    resource: "Player",
    action: "update",
    possession: "any",
  })
  async updatePlayerGroups(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: PlayerGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      playerGroups: {
        set: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/playerGroups")
  @nestAccessControl.UseRoles({
    resource: "Player",
    action: "update",
    possession: "any",
  })
  async disconnectPlayerGroups(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: PlayerGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      playerGroups: {
        disconnect: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/playerLocations")
  @ApiNestedQuery(PlayerLocationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PlayerLocation",
    action: "read",
    possession: "any",
  })
  async findPlayerLocations(
    @common.Req() request: Request,
    @common.Param() params: PlayerWhereUniqueInput
  ): Promise<PlayerLocation[]> {
    const query = plainToClass(PlayerLocationFindManyArgs, request.query);
    const results = await this.service.findPlayerLocations(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        location: {
          select: {
            id: true,
          },
        },

        player: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/playerLocations")
  @nestAccessControl.UseRoles({
    resource: "Player",
    action: "update",
    possession: "any",
  })
  async connectPlayerLocations(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: PlayerLocationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      playerLocations: {
        connect: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/playerLocations")
  @nestAccessControl.UseRoles({
    resource: "Player",
    action: "update",
    possession: "any",
  })
  async updatePlayerLocations(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: PlayerLocationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      playerLocations: {
        set: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/playerLocations")
  @nestAccessControl.UseRoles({
    resource: "Player",
    action: "update",
    possession: "any",
  })
  async disconnectPlayerLocations(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: PlayerLocationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      playerLocations: {
        disconnect: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }
}
