/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { GameActionListRelationFilter } from "../../gameAction/base/GameActionListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { PlayerGroupListRelationFilter } from "../../playerGroup/base/PlayerGroupListRelationFilter";
import { PlayerLocationListRelationFilter } from "../../playerLocation/base/PlayerLocationListRelationFilter";

@InputType()
class PlayerWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  email?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => GameActionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => GameActionListRelationFilter)
  @IsOptional()
  @Field(() => GameActionListRelationFilter, {
    nullable: true,
  })
  gameActions?: GameActionListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  nickname?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => PlayerGroupListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PlayerGroupListRelationFilter)
  @IsOptional()
  @Field(() => PlayerGroupListRelationFilter, {
    nullable: true,
  })
  playerGroups?: PlayerGroupListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => PlayerLocationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PlayerLocationListRelationFilter)
  @IsOptional()
  @Field(() => PlayerLocationListRelationFilter, {
    nullable: true,
  })
  playerLocations?: PlayerLocationListRelationFilter;
}

export { PlayerWhereInput as PlayerWhereInput };
