/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  ValidateNested,
  MaxLength,
} from "class-validator";
import { GameActionCreateNestedManyWithoutPlayersInput } from "./GameActionCreateNestedManyWithoutPlayersInput";
import { Type } from "class-transformer";
import { PlayerGroupCreateNestedManyWithoutPlayersInput } from "./PlayerGroupCreateNestedManyWithoutPlayersInput";
import { PlayerLocationCreateNestedManyWithoutPlayersInput } from "./PlayerLocationCreateNestedManyWithoutPlayersInput";

@InputType()
class PlayerCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => GameActionCreateNestedManyWithoutPlayersInput,
  })
  @ValidateNested()
  @Type(() => GameActionCreateNestedManyWithoutPlayersInput)
  @IsOptional()
  @Field(() => GameActionCreateNestedManyWithoutPlayersInput, {
    nullable: true,
  })
  gameActions?: GameActionCreateNestedManyWithoutPlayersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nickname?: string | null;

  @ApiProperty({
    required: false,
    type: () => PlayerGroupCreateNestedManyWithoutPlayersInput,
  })
  @ValidateNested()
  @Type(() => PlayerGroupCreateNestedManyWithoutPlayersInput)
  @IsOptional()
  @Field(() => PlayerGroupCreateNestedManyWithoutPlayersInput, {
    nullable: true,
  })
  playerGroups?: PlayerGroupCreateNestedManyWithoutPlayersInput;

  @ApiProperty({
    required: false,
    type: () => PlayerLocationCreateNestedManyWithoutPlayersInput,
  })
  @ValidateNested()
  @Type(() => PlayerLocationCreateNestedManyWithoutPlayersInput)
  @IsOptional()
  @Field(() => PlayerLocationCreateNestedManyWithoutPlayersInput, {
    nullable: true,
  })
  playerLocations?: PlayerLocationCreateNestedManyWithoutPlayersInput;
}

export { PlayerCreateInput as PlayerCreateInput };
