/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PlayerLocationService } from "../playerLocation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PlayerLocationCreateInput } from "./PlayerLocationCreateInput";
import { PlayerLocation } from "./PlayerLocation";
import { PlayerLocationFindManyArgs } from "./PlayerLocationFindManyArgs";
import { PlayerLocationWhereUniqueInput } from "./PlayerLocationWhereUniqueInput";
import { PlayerLocationUpdateInput } from "./PlayerLocationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PlayerLocationControllerBase {
  constructor(
    protected readonly service: PlayerLocationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PlayerLocation })
  @nestAccessControl.UseRoles({
    resource: "PlayerLocation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPlayerLocation(
    @common.Body() data: PlayerLocationCreateInput
  ): Promise<PlayerLocation> {
    return await this.service.createPlayerLocation({
      data: {
        ...data,

        location: data.location
          ? {
              connect: data.location,
            }
          : undefined,

        player: data.player
          ? {
              connect: data.player,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        location: {
          select: {
            id: true,
          },
        },

        player: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PlayerLocation] })
  @ApiNestedQuery(PlayerLocationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PlayerLocation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async playerLocations(
    @common.Req() request: Request
  ): Promise<PlayerLocation[]> {
    const args = plainToClass(PlayerLocationFindManyArgs, request.query);
    return this.service.playerLocations({
      ...args,
      select: {
        createdAt: true,
        id: true,

        location: {
          select: {
            id: true,
          },
        },

        player: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PlayerLocation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PlayerLocation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async playerLocation(
    @common.Param() params: PlayerLocationWhereUniqueInput
  ): Promise<PlayerLocation | null> {
    const result = await this.service.playerLocation({
      where: params,
      select: {
        createdAt: true,
        id: true,

        location: {
          select: {
            id: true,
          },
        },

        player: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PlayerLocation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PlayerLocation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePlayerLocation(
    @common.Param() params: PlayerLocationWhereUniqueInput,
    @common.Body() data: PlayerLocationUpdateInput
  ): Promise<PlayerLocation | null> {
    try {
      return await this.service.updatePlayerLocation({
        where: params,
        data: {
          ...data,

          location: data.location
            ? {
                connect: data.location,
              }
            : undefined,

          player: data.player
            ? {
                connect: data.player,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          location: {
            select: {
              id: true,
            },
          },

          player: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PlayerLocation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PlayerLocation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePlayerLocation(
    @common.Param() params: PlayerLocationWhereUniqueInput
  ): Promise<PlayerLocation | null> {
    try {
      return await this.service.deletePlayerLocation({
        where: params,
        select: {
          createdAt: true,
          id: true,

          location: {
            select: {
              id: true,
            },
          },

          player: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
